### PR TITLE
Fixes #1203

### LINKED ISSUE #1203: Infinispan client/server App as quickstart
I'm currently working on a little quickstart related to an Infinispan client/server app.

I would like to add a couple of maven modules: one with the client and one with the server.

Talking with @jstrachan the best idea is to keep Infinispan server as a sidecar container. So this issue is related to https://github.com/fabric8io/fabric8-maven-plugin/issues/17

For the early stage I think we can push the two modules separated and then work on a combined version with the server as sidecar container.

The client actually works on a local cache. I hope this can be a good quickstart for folks who wants to use fabric8 in scenarios like these

### PR DESCRIPTION
**Pull request by oscerd**
Completed Infinispan quickstart related to #1203.

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by jstrachan** [comment]
add to whitelist

**Comment by oscerd** [comment]
retest this please

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
