### PR TITLE
[OSFUSE-375|OSFUSE-376]add cxf spring-boot quickstarts

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
@rawlingsj  could you please help to merge this PR?
Thanks!

**Comment by jstrachan** [comment]
BTW we don't usually add any source for the archetype in the `archetypes/foo/src` folder - we use a `.gitignore` file to hide that stuff. e.g.  https://github.com/fabric8io/ipaas-quickstarts/tree/master/archetypes/cdi-cxf-archetype

we could merge this then delete the src folder, unless you fancy updating your PR to remove the src folders?

**Comment by jstrachan** [comment]
I think the reason for the `src` folder being added by accident was you didn't add the `.gitignore` file that gets generated - e.g. https://github.com/ffang/quickstarts/blob/4c6e8d90f84de04bc5488840faa48750787e77c4/archetypes/cdi-cxf-archetype/.gitignore

any chance you could remove the `src` folder and add the `.gitgnore` instead?

**Comment by ffang** [comment]
Thanks @jstrachan !

And @rawlingsj also told me the src example should be put into another github repository [1]

Seems I need firstly create spring-boot-cxf-jaxrs and spring-boot-cxf-jaxrs project in[1] and then revise this PR accordingly.

Can I have permission to create projects in[1] myself or I need somehow attach the projects so that admins of [1] can create it? 
[1]https://github.com/fabric8-quickstarts.

**Comment by ffang** [comment]
This PR was revised accordingly

**Comment by kcbabo** [comment]
Out of curiosity, is it possible to use CXF underneath the Spring MVC annotations?  So use \@RestController and \@RequestMapping in the app, but have that wire into CXF under the covers?

**Comment by ffang** [comment]
@kcbabo No, it's not possible.

IMO Spring MVC and CXF Restful(JAX-RS spec impl) are different frameworks and they have different strength by design. CXF Restful is designed for web service(mostly json payload based) for a thin client to consume, on the other hand the Spring MVC is designed for the web application(html page based and that's why the MVC is important here) for a rich client(like browser) to consume. And it's hard to do a one to one map between the Spring MVC annotation and the JAXRS annotation.

**Comment by ffang** [comment]
[merge]

**Comment by ffang** [comment]
I thought manually click "merge" button will trigger the CI build, but this just merged without any CI build, I will revert this merge and create another PR

**Comment by kcbabo** [comment]
Thanks @ffang.  Just for clarity, the REST annotations in Spring MVC are functionally the same as JAX-RS annotations, e.g. 
https://spring.io/guides/gs/rest-service/

I'm not sure why Spring chose to put them in MVC, but these annotations are definitely meant for RESTful web services and not for UI-based web apps.  Just something to consider.  Great to see that we have CXF annotations working directly with Boot apps.

**Pull request merged**
