### PR TITLE
added dotnet examples

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
[merge]

**Comment by rawlingsj** [comment]
ah thanks @jstrachan!  I forgot this, I'll add one in for the php example too.

**Comment by rawlingsj** [comment]
ok so you'd already done the php one :)

**Comment by jstrachan** [comment]
@rawlingsj np! :) BTW if you do a mvn build in the archetypes-catalog folder it now tells you what to do to enable missing archeytypes:
```
WARNING the following archetypes were not added to the archetypes catalog: [dotnet-example-archetype, swarm-camel-archetype]

To add them please type the following commands into the terminal:

git add archetypes/dotnet-example-archetype
git add archetypes/swarm-camel-archetype

Then add the following XML into the archetypes/pom.xml file in the <modules> element:

    <module>dotnet-example-archetype</module>
    <module>swarm-camel-archetype</module>

Then git commit and submit a PR please!
```

**Comment by rawlingsj** [comment]
Perfect - that's a much easier way to figure out what's missing.  Thanks!

**Pull request merged**
