### PR TITLE
Tease apart archetype and catalog generation, so we can generate the Catalog after the artifacts are built so we only include built archetypes in the catalog.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
[lgtm][merge]

**Comment by christian-posta** [comment]
[merge]

**Comment by jimmidyson** [comment]
[merge]

**Comment by jstrachan** [comment]
BTW to make the archetypes get built first we could just change the order in the parent pom
https://github.com/fabric8io/ipaas-quickstarts/blob/master/pom.xml#L101

**Pull request merged**
