### PR TITLE
Removed karaf quickstarts, added karaf jboss-fuse archetypes

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
@dhirajsb sorry I missed this PR! any chance you could rebase and push again please?

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
@jstrachan rebased, not sure why it's still failing

**Comment by dhirajsb** [comment]
@jstrachan ok, after fixing some minor build issues, it looks like it's failing because it can't resolve jboss-fuse artifacts

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
ok to test

**Comment by dhirajsb** [comment]
@jstrachan not sure why it keeps failing, runs fine locally. The log says there are no folders under git-clones, when previous lines show repos being cloned!

**Comment by jimmidyson** [comment]
Problem was Jenkins cleaning stuff out after checkout which meant modules weren't enabled properly for build. Fixed now.

**Comment by jimmidyson** [comment]
@dhirajsb Needs a rebase please.

**Comment by jimmidyson** [comment]
And please make sure SNAPSHOT versions are 2.2-SNAPSHOT now,

**Comment by dhirajsb** [comment]
[merge]

**Comment by rhuss** [comment]
[merge]

**Comment by dhirajsb** [comment]
retest this please

**Comment by dhirajsb** [comment]
[merge]

**Comment by rhuss** [comment]
[merge]

**Pull request merged**
