### PR TITLE
Use java 1.8

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
[merge]

**Comment by jimmidyson** [comment]
Nice - didn't know we'd decided to start ditching 1.7?

**Comment by rhuss** [comment]
Its probably a preparation for Camel 2.18 ?

**Comment by davsclaus** [comment]
all our base images runs on java 8, and we should get on board using java 8 to make those part of fabric8 up to date.

**Comment by davsclaus** [comment]
Anyone see a potential issue? Have I missed something?

**Pull request merged**
