### PR TITLE
Simplify archetype build profiles so that we build them all by default

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by jstrachan** [comment]
Please don't merge this PR yet anyone!

We need to cut a working release first since previous profile logic broke the release build.

After that if we can pass in the new community profile in our CD infrastructure we can try use this PR

**Comment by jstrachan** [comment]
@chirino any chance you could rebase please?

**Comment by chirino** [comment]
rebased.

**Comment by chirino** [comment]
retest this please

**Pull request merged**
