### PR TITLE
Created a Camel-Teiid quickstart

### PR DESCRIPTION
**Pull request by nicolaferraro**
I created a quickstart showing how Camel and Teiid can be used together in a spring-boot application running on fabric8.

In the sample application, two (sample) embedded H2 database instances are created and linked together through a Teiid virtual database layer.
A camel route periodically generates a random input and queries the virtual database to
compute intermediate routing information.

### CODE REVIEW

**Comment by oscerd** [comment]
Awesome :-)

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
This PR fails due some JARs cannot be found in maven central

```
ERROR MavenCli                       - Failed to execute goal on project spring-boot-camel-teiid-archetype: Could not resolve dependencies for project io.fabric8.archetypes:spring-boot-camel-teiid-archetype:jar:2.3-SNAPSHOT: The following artifacts could not be resolved: org.jboss.teiid:teiid-runtime:jar:9.0.0.Final, org.jboss.teiid.connectors:translator-jdbc:jar:9.0.0.Final: Could not find artifact org.jboss.teiid:teiid-runtime:jar:9.0.0.Final in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Where are those JARs ?

**Comment by nicolaferraro** [comment]
I forgot I had JBoss public repo configured in settings (Teiid is hosted there, only). 

Now it should be ok.

**Comment by davsclaus** [comment]
[merge]

**Pull request merged**
