### PR TITLE
Upgrade Docker Maven plugin to version 0.13.7

### PR DESCRIPTION
**Pull request by oscerd**
Upgrade Docker Maven plugin to version 0.13.7.

Related to: https://github.com/fabric8io/fabric8/issues/5402

Andrea

### CODE REVIEW

**Comment by oscerd** [comment]
It seems there is no space on CI machine.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project quickstart-cdi-camel-mq: Failed to install artifact io.fabric8.quickstarts:quickstart-cdi-camel-mq:tar.gz:app:2.2.73-SNAPSHOT: No space left on device -> [Help 1]

**Comment by jimmidyson** [comment]
We're probably `mvn install`ing too much stuff as part of this build. This is a free service so understandable it has limits.

Can we change the build to `verify` rather than `install`?

**Comment by jimmidyson** [comment]
We might also need to disable the m2 cache on circleci - not sure how to do that though, but it gets cached & loaded on every build so might be pretty big by now.

**Comment by rhuss** [comment]
Guess it can be done with sth like:

```
dependencies:
  post:
    - rm -r ~/.m2
```

as suggested on https://circleci.com/docs/how-cache-works

**Comment by rhuss** [comment]
Maybe we can remove only the created artefacts ? 

```
dependencies:
  post:
    - rm -r ~/.m2/repository/io/fabric8
```

**Comment by rhuss** [comment]
Ok, its not circle CI but our own Jenkins. So one probably have to cleanup there ;)

**Comment by jimmidyson** [comment]
There's a m2 slave cleanup job IIRC - try running that then retesting.

BTW I've raised a ticket with eng ops to sort out the disks.

**Comment by oscerd** [comment]
If needed, I can rebase the PR and the push again to start the testing whenever the cleanup is done

**Comment by jimmidyson** [comment]
@oscerd Thanks but we should be able to retrigger without you doing anything.

**Comment by jimmidyson** [comment]
retest this please

**Pull request merged**
