### PR TITLE
Update pom property fabric8.version to 2.2.179

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge] lgtm

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Comment by davsclaus** [comment]
Ah forgot this was not yet merged, but when it is this should be mergable also
https://github.com/fabric8io/ipaas-quickstarts/pull/1467

**Pull request merged**
