### PR TITLE
More work on Vert.x quickstarts

### PR DESCRIPTION
**Pull request by purplefox**
Implement a clustered chat and a clustered eventbus example.

These examples use the Hazelcast k8s discovery plugin to locate other Vert.x/HZ nodes in the k8s cluster.

Note that the HZ k8s plugin is only available in >= HZ 3.6 so we override the transitive HZ dependency to include HZ 3.6-EA2. Also we rely on a snapshot for the discovery plugin itself as the previous DNS lookup functionality was broken (fixed by @jimmidyson)

### CODE REVIEW

**Comment by jimmidyson** [comment]
You've got the wrong version of the parent pom. Can you update please?

**Comment by rawlingsj** [comment]
I'm not sure about the `hazelcast-kubernetes-discovery` SNAPSHOT version but I've just kicked off a fabric8io/fabric project release so you will be able to remove the fabric8.version SNAPSHOT in an hour or so.

We need to avoid snapshot versions in poms as they'll break the release.  There's a fabric8 snapshot profile we can use when developing and changes exist in a local upstream project https://github.com/purplefox/ipaas-quickstarts/blob/master/pom.xml#L254

**Comment by rawlingsj** [comment]
@purplefox I've added you to the slack team we use for the fabric8 CD release.  If you want to then you can get notifications when releases are available in maven central etc.

**Comment by jimmidyson** [comment]
Yeah we should ask for a release of the hz plugin.

**Comment by rawlingsj** [comment]
Ah cool - yeah if we can avoid merging this till thats been released that would be great.

**Comment by jimmidyson** [comment]
noctarius/hazelcast-kubernetes-discovery#7

**Comment by rawlingsj** [comment]
io/fabric8/fabric8-maven-plugin 2.2.85 released and available in maven central

**Comment by davsclaus** [comment]
Are those plugins and whatnot released? Or is this PR gone stale, if so should we close it?

**Comment by rawlingsj** [comment]
closing at PR is stale

**Pull request closed without merging**
