### PR TITLE
Added a SOAP examle from http://camel.apache.org/spring-ws-example.html

### PR DESCRIPTION
**Pull request by stevef1uk**
Just thought I would try to share this.

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by stevef1uk** [comment]
Added a couple more example projects

**Comment by davsclaus** [comment]
SOAP is too old school. Can you create new PR per new example so its easier to review and merge.
For example an JAX-RS example for spring-boot etc.

Going to close this PR

**Comment by stevef1uk** [comment]
Your choice. Most enterprises that I work in still have their core business logic exposed by SOAP.

I did also add a JAX-RS example.

**Comment by jimmidyson** [comment]
@davsclaus Do you feel really strongly about not having a SOAP example? I agree it's old & crusty, but as @stevef1uk says it's still widely used. Personally I think we should keep it in as long as it does not mean loads of work maintaining it.

**Comment by davsclaus** [comment]
Yes I am worry if we end up with too many quickstarts to maintain and too many archetypes.
People should be able to develop without having a quickstart for everything.

Its imho better to have a quickstart that setup the technology stack of choice, eg spring-boot / widlfly / standalone. And then if you need SOAP etc then there is some tooling that can add SOAP to any existing Java project. In fact Eclipse / IDEA have some plugins/tools for that and also JBoss Tools.

Also for SOAP there is a difference between hosting a SOAP service or calling an existing. Would you then need a quickstart for each kind?

**Pull request closed without merging**
