### PR TITLE
Add Spring Boot Camel REST SQL archetype

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
looks like we can't merge due to test failures right now for this archetype

**Comment by astefanutti** [comment]
Yes that new archetype tests are OK though it looks like the `jboss-fuse-cxf-rest` archetype tests are failing. Let me see what I can do.

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jstrachan** [comment]
@astefanutti I disabled the failing `jboss-fuse-cxf-rest` archetype for now:  https://github.com/fabric8io/ipaas-quickstarts/pull/1408 we can revert that commit whenever this issue is fixed https://github.com/fabric8-quickstarts/jboss-fuse-cxf-rest/issues/25

**Comment by jstrachan** [comment]
add to whitelist

**Comment by jstrachan** [comment]
if this PR doesn't go through this build, then rebasing it and pushing again hopefully will ;)

**Comment by astefanutti** [comment]
@jstrachan thanks a lot! I've rebased and repushed. Though it seems the CI job is stuck for some reasons 😢.

**Comment by jstrachan** [comment]
@astefanutti it worked! its just kinda slow ;)

**Comment by jstrachan** [comment]
[merge]

**Comment by astefanutti** [comment]
I confused slowness for stuckness 😄. Thanks a lot for the merge! I'll look at the failing archetype ASAP.

**Pull request merged**
