### PR TITLE
Revert "#956: Switch to java-s2i image, fixed console and s2i build"

### PR DESCRIPTION
**Pull request by nicolaferraro**
Reverts fabric8io/ipaas-quickstarts#1254

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

Thanks @nicolaferraro!

**Comment by nicolaferraro** [comment]
Probably you forgot to merge these changes...

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Let's try again.. [merge]

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
