### PR TITLE
Add service annotations to quickstarts that have a service descriptio…

### PR DESCRIPTION
**Pull request by KurtStam**
…n document #1175

### CODE REVIEW

**Comment by KurtStam** [comment]
[merge]

**Comment by jstrachan** [comment]
add to whitelist

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
@KurtStam think you maybe need a rebase?

**Comment by davsclaus** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
