### PR TITLE
[OSFUSE-375|OSFUSE-376]add cxf spring-boot quickstarts archetypes

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
[merge]

**Comment by ffang** [comment]
[lgtm][merge]

**Comment by ffang** [comment]
Hi @jstrachan, @rawlingsj 

Could you please trigger CI to build and merge this PR?
Thanks!

**Comment by jstrachan** [comment]
add to whitelist

**Comment by jstrachan** [comment]
[merge]

**Pull request merged**
