### PR TITLE
OSFUSE-306: renaming the archetypes to remove references to JBoss Fuse

### PR DESCRIPTION
**Pull request by nicolaferraro**
Renaming the archetypes to reflect the new name of the quickstarts.
This can be merged before changing the repository names.

### CODE REVIEW

**Comment by rawlingsj** [comment]
ok to test

**Comment by nicolaferraro** [comment]
@rawlingsj thanks, but it seems that the projects need to be renamed first. It worked on my machine because the module folders were not empty, but there is a gitignore preventing it to be committed on git.

I'll ask you to retest later. Thanks.

**Comment by rawlingsj** [comment]
retest this please

**Comment by rawlingsj** [comment]
[merge]

**Pull request merged**
